#Menu do while.
def menuPrimario():
    print("_____________________________________")
    print("--------- Agenda de contato ---------")
    print("------ Seja Bem-vindo a Agenda ------")
    print("------------- MENU ------------------")
    print("_____________________________________")
    print("| 1. Cadastrar um contato           |")
    print("|-----------------------------------|")
    print("| 2. Procurar um contato            |")
    print("|-----------------------------------|")
    print("| 3. Alterar um contato             |")
    print("|-----------------------------------|")
    print("| 4. Excluir um contato             |")
    print("|-----------------------------------|")
    print("| 5. Listar todos contatos          |")
    print("|-----------------------------------|")
    print("| 6. Sair                           |")
    print("_____________________________________")
    
    
#Menu de opções para listar contatos.
def menuSegundario():
    print("_________________________________________")
    print("----------- Agenda de contato -----------")
    print("-----------------------------------------")
    print("| 1. Listando todos contatos            |")
    print("|---------------------------------------|")
    print("| 2. Listando todos contatos por arquivo|")
    print("|---------------------------------------|")
    print("| 3. Sair                               |")
    print("_________________________________________")
    
    
#Menu para opções de excluir um contato.
def menuTerciario():
    print("__________________________________________")
    print("----------- Excluindo contato ------------")
    print("------------------------------------------")
    print("| 1. Excluindo  contato na lista         |")
    print("|----------------------------------------|")
    print("| 2. Excluindo todos contatos de arquivos|")
    print("|----------------------------------------|")
    print("| 3. Sair                                |")
    print("__________________________________________")
    
    
#Menu para alterar contatos
def quartoMenu():
    print("_______________________________________________")
    print("--------------- Alterar contato ---------------")
    print("-----------------------------------------------")
    print("| 1. Alterar nome                             |")
    print("|---------------------------------------------|")
    print("| 2. Alterar sobrenome                        |")
    print("|---------------------------------------------|")
    print("| 3. Alterar apelido                          |")
    print("|---------------------------------------------|")
    print("| 4. Alterar número de celular                |")
    print("|---------------------------------------------|")
    print("| 5. Alterar país                             |")
    print("|---------------------------------------------|")
    print("| 6. Alterar estado                           |")
    print("|---------------------------------------------|")
    print("| 7. Alterar cidade                           |")
    print("|---------------------------------------------|")
    print("| 8. Alterar nome da rua                      |")
    print("|---------------------------------------------|")
    print("| 9. Alterar número da casa                   |")
    print("|---------------------------------------------|")
    print("| 10. Alterar o bairro                        |")
    print("|---------------------------------------------|")
    print("| 11. Alterar o CEP                           |")
    print("|---------------------------------------------|")
    print("| 12. Sair                                    |")
    print("_______________________________________________")
